/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import OctoAModel from '../../static/assets/models/OCT.glb'


export function OctoA(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(OctoAModel);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature001" position={[0, 0.12, 0]}>
          <primitive object={nodes.Bone} />
          <primitive object={nodes.Bone020} />
          <primitive object={nodes.Bone040} />
          <primitive object={nodes.Bone060} />
          <primitive object={nodes.Bone080} />
          <primitive object={nodes.Bone100} />
          <primitive object={nodes.Bone120} />
          <primitive object={nodes.Bone140} />
          <primitive object={nodes.Bone160} />
          <group name="OCTOPUS001" position={[0, -0.12, 0]}>
            <skinnedMesh
              name="Cube003"
              geometry={nodes.Cube003.geometry}
              material={materials.MAIN}
              skeleton={nodes.Cube003.skeleton}
            />
            <skinnedMesh
              name="Cube003_1"
              geometry={nodes.Cube003_1.geometry}
              material={materials.UNDERSIDE}
              skeleton={nodes.Cube003_1.skeleton}
            />
            <skinnedMesh
              name="Cube003_2"
              geometry={nodes.Cube003_2.geometry}
              material={materials["EYES.001"]}
              skeleton={nodes.Cube003_2.skeleton}
            />
            <skinnedMesh
              name="Cube003_3"
              geometry={nodes.Cube003_3.geometry}
              material={materials.DOTS}
              skeleton={nodes.Cube003_3.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(OctoAModel);